module: Adyen
author: Adyen
author_url: https://adyen.com
github_url: https://github.com/Adyen/adyen-ios

readme: README.md

output: Docs
theme: fullwidth
skip_undocumented: false
hide_documentation_coverage: true

custom_categories:
  
  - name: Drop In Component
    children:
      - DropInComponent
      - DropInComponentDelegate
      
  - name: Payment Methods
    children:
      - PaymentMethod
      - PaymentMethods
      - StoredPaymentMethod
      - StoredCardPaymentMethod
      - StoredBCMCPaymentMethod
      - StoredPayPalPaymentMethod
      - StoredBLIKPaymentMethod
      - AnyCardPaymentMethod
      - CardPaymentMethod
      - BCMCPaymentMethod
      - IssuerListPaymentMethod
      - ApplePayPaymentMethod
      - SEPADirectDebitPaymentMethod
      - QiwiWalletPaymentMethod
      - AwaitPaymentMethod
      - MBWayPaymentMethod
      - BLIKPaymentMethod
      - VoucherPaymentMethod
      - DokuPaymentMethod
      - EContextATMPaymentMethod
      - SevenElevenPaymentMethod
      - EContextStoresPaymentMethod
      - EContextOnlinePaymentMethod
      - QRCodePaymentMethod
      - WeChatPayPaymentMethod
      
  - name: Actions
    children:
      - Action
      - AdyenActionComponent
      - ActionComponentData
      - ActionComponentDelegate
      - RedirectAction
      - RedirectComponent
      - ThreeDS2Action
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction
      - AwaitAction
      - AwaitComponent
      - GenericVoucherAction
      - VoucherComponent
      - VoucherAction
      - QRCodeAction
      - QRCodeComponent
      - SDKAction
      - WeChatPaySDKActionComponent
      - WeChatPaySDKAction
      
  - name: 3D Secure 2 Component
    children:
      - ThreeDS2Component
      - ThreeDS2ComponentError
      - ThreeDS2Details
      - ThreeDS2Action
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction
      
  - name: Card Component
    children:
      - CardComponent
      - BCMCComponent
      - CardDetails
      - CardType
      - CardBrand
      - CardExpiryDateFormatter
      - CardExpiryDateValidator
      - CardSecurityCodeFormatter
      - CardSecurityCodeValidator
      - CardNumberFormatter
      - CardNumberValidator
      - CardComponentDelegate
      - StoredCardConfiguration
      
  - name: Apple Pay Component
    children:
      - ApplePayPaymentMethod
      - ApplePayComponent
      - ApplePayDetails
      
  - name: Qiwi Wallet Component
    children:
      - QiwiWalletPaymentMethod
      - QiwiWalletComponent
      - QiwiWalletDetails
      
  - name: MB Way Component
    children:
      - MBWayPaymentMethod
      - MBWayComponent
      - MBWayDetails
      
  - name: BLIK Component
    children:
      - BLIKPaymentMethod
      - StoredBLIKPaymentMethod
      - BLIKComponent
      - BLIKDetails
      
  - name: Doku Component
    children:
      - DokuPaymentMethod
      - DokuComponent
      - DokuDetails
      
  - name: PIX Component
    children:
      - PixComponent
      - DokuDetails
      
  - name: SEPA Direct Debit Component
    children:
      - SEPADirectDebitComponent
      - SEPADirectDebitDetails
      - IBANFormatter
      - IBANValidator
      
  - name: WeChat Pay
    children:
      - WeChatPaySDKData
      - WeChatPayPaymentMethod
      - WeChatPaySDKActionComponent
      - WeChatPaySDKAction
      
  - name: Issuer List Component
    children:
      - IssuerListComponent
      - IdealComponent
      - MOLPayComponent
      - DotpayComponent
      - EPSComponent
      - EntercashComponent
      - OpenBankingComponent
      - EntercashDetails
      - OpenBankingDetails
      - EPSDetails
      - DotpayDetails
      - MOLPayDetails
      - IdealDetails
      - IssuerListDetails
      
  - name: EContext Components
    children:
      - EContextATMComponent
      - EContextOnlineComponent
      - EContextStoreComponent
      
  - name: Seven Eleven Component
    children:
      - SevenElevenComponent
      
  - name: Payment Details
    children:
      - Details
      - PaymentMethodDetails
      - RedirectDetails
      - AdditionalDetails
      - AwaitActionDetails
      - EntercashDetails
      - OpenBankingDetails
      - EPSDetails
      - DotpayDetails
      - MOLPayDetails
      - IdealDetails
      - IssuerListDetails
      - SEPADirectDebitDetails
      - DokuDetails
      - BLIKDetails
      - QiwiWalletDetails
      - ApplePayDetails
      - ThreeDS2Details
      
  - name: Base Component
    children:
      - Component
      - PaymentComponent
      - PresentableComponent
      - FinalizableComponent
      - PaymentAwareComponent
      - TrackableComponent
      - PaymentComponentDelegate
      - PresentationDelegate
      - PartialPaymentDelegate
      - PartialPaymentComponent
      - ActionComponent
      - VoucherComponent
      - BasicPersonalInfoFormComponent
      
  - name: Models
    children:
      - ShopperInteraction
      - DisplayInformation
      - PaymentComponentData
      - Payment
      - CardFundingSource
      - BrowserInfo
      - ShopperName
      - AddressInfo
      - ShopperInformation
      - BillingAddressInformation
      - LocalizationParameters
      - PaymentOrder
      
  - name: Styling
    children:
      - FormComponentStyle
      - FormHeaderStyle
      - FormFooterStyle
      - FormTextItemStyle
      - FormSwitchItemStyle
      - FormButtonItemStyle
      - ListComponentStyle
      - ListSectionHeaderStyle
      - ListItemStyle
      - AwaitComponentStyle
      - RedirectComponentStyle
      - VoucherComponentStyle
      - QRCodeComponentStyle
      - NavigationStyle
      - ToolbarMode
      - ButtonStyle
      - CancelButtonStyle
      - ImageStyle
      - TextStyle
      - ViewStyle
      - TintableStyle
      - ProgressViewStyle
      - CornerRounding
      
  - name: Encryption
    children:
      - CardEncryptor
      - Card
      - EncryptedCard
      
  - name: Utilities
    children:
      - AdyenLogging
      - Formatter
      - Validator
      - LengthValidator
      - Environment
      - LogoURLProvider
      - ComponentError
      - SecuredViewController
      - Localizable
